server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WarnerHooh/amaz-config.git
          search-paths: 'app-configs/{application}'
          timeout: 60
          clone-on-start: true
          force-pull: true
          basedir: /tmp/amaz-config/app-configs

